### ISSUE TITLE
Links that need fixing

### ISSUE THREAD

**Issue by p9g** [HL7/cqf-measures#229]
https://github.com/HL7/cqf-measures/blob/master/input/pages/measure-repository-service.md?plain=1#L12-L24

Link text at https://github.com/HL7/cqf-measures/blob/master/input/pages/measure-repository-service.md?plain=1#L83 is misspelled
s/CRMIAuthoringArtifactReposiotry/CRMIAuthoringArtifactRepository/

**Comment by abdullah-git1** [comment]
Link has been resolved
